version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 33061:3306
    networks:
      - java_network
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - java_network
  userservice:
    container_name: userservice
    image: userservice
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    environment:
      - NAME=Docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - java_network
networks:
  java_network:
    name: java_network


